### ISSUE TITLE
Make ARC happy

### ISSUE THREAD

**Issue by inuradz** [WeilonYing/UNSW-Minecraft-Society-Discord-Verification-Bot#7]
We need that 10/10  so time for voice commands.

I had to type and it didn't accept voice commands. Sort of lacking polish but worth the price. 9/10. -IGN - @Steveyboi

![image](https://user-images.githubusercontent.com/11470833/77049948-13fa7b80-6a1d-11ea-84c9-4ccabfe56070.png)

**Comment by WeilonYing** [comment]
Unfortunately, integrating this with a service that does voice transcription would be too costly in time and effort, given the resulting benefit. Closing this issue.
